forrtl: Input/output error
forrtl: severe (30): open failure, unit 10, file /users/bohn/jacr7386/for_john/data/Jfec_AlkaliDimerDimer/7Li41K_7Li41K/fort.10
Image              PC                Routine            Line        Source             
1d_schrodinger.x   00000000004995BA  Unknown               Unknown  Unknown
1d_schrodinger.x   0000000000498135  Unknown               Unknown  Unknown
1d_schrodinger.x   00000000004681D6  Unknown               Unknown  Unknown
1d_schrodinger.x   0000000000443E95  Unknown               Unknown  Unknown
1d_schrodinger.x   0000000000443651  Unknown               Unknown  Unknown
1d_schrodinger.x   0000000000420DC6  Unknown               Unknown  Unknown
1d_schrodinger.x   0000000000404643  Unknown               Unknown  Unknown
1d_schrodinger.x   00000000004032FC  Unknown               Unknown  Unknown
libc.so.6          00007F1105391CDD  Unknown               Unknown  Unknown
1d_schrodinger.x   00000000004031F9  Unknown               Unknown  Unknown
Traceback (most recent call last):
  File "rovib.py", line 44, in <module>
    run_1d_schrodinger(inputfile,outputfile,i)
  File "rovib.py", line 32, in run_1d_schrodinger
    replace(inputfile_name, ' L', L) #editing inputfile such that L=L is called
  File "rovib.py", line 26, in replace
    shutil.move(abs_path, file)
  File "/usr/lib64/python2.6/shutil.py", line 260, in move
    copy2(src, real_dst)
  File "/usr/lib64/python2.6/shutil.py", line 95, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.6/shutil.py", line 51, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 5] Input/output error: 'input.txt'
